# Source: https://github.com/per1234/.github/blob/main/workflow-templates/check-toc.md
name: Check ToC

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-toc.ya?ml"
      - "README.md"
  pull_request:
    paths:
      - ".github/workflows/check-toc.ya?ml"
      - "README.md"
  workflow_dispatch:
  repository_dispatch:

jobs:
  check:
    name: ${{ matrix.file.name }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      fail-fast: false

      matrix:
        file:
          - name: README.md
            # Max ToC depth, for use with the markdown-toc --maxdepth flag.
            maxdepth: 4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install markdown-toc
        run: sudo npm install --global markdown-toc

      - name: Rebuild ToC
        run: |
          markdown-toc \
            --bullets=- \
            --maxdepth=${{ matrix.file.maxdepth }} \
            -i \
            "${{ github.workspace }}/${{ matrix.file.name }}"

      - name: Check ToC
        run: git diff --color --exit-code
